/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinkRouteImport } from './routes/link'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TosIndexRouteImport } from './routes/tos.index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy.index'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthDiscordIndexRouteImport } from './routes/api/auth/discord/index'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord/callback'

const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TosIndexRoute = TosIndexRouteImport.update({
  id: '/tos/',
  path: '/tos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordIndexRoute = ApiAuthDiscordIndexRouteImport.update({
  id: '/api/auth/discord/',
  path: '/api/auth/discord/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/api/auth/discord/callback',
  path: '/api/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/link': typeof LinkRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/tos/': typeof TosIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/': typeof ApiAuthDiscordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/link': typeof LinkRoute
  '/privacy': typeof PrivacyIndexRoute
  '/tos': typeof TosIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord': typeof ApiAuthDiscordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/link': typeof LinkRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/tos/': typeof TosIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/': typeof ApiAuthDiscordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/link'
    | '/privacy/'
    | '/tos/'
    | '/api/auth/logout'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/link'
    | '/privacy'
    | '/tos'
    | '/api/auth/logout'
    | '/api/auth/discord/callback'
    | '/api/auth/discord'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/link'
    | '/privacy/'
    | '/tos/'
    | '/api/auth/logout'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  LinkRoute: typeof LinkRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  TosIndexRoute: typeof TosIndexRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
  ApiAuthDiscordIndexRoute: typeof ApiAuthDiscordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos/': {
      id: '/tos/'
      path: '/tos'
      fullPath: '/tos/'
      preLoaderRoute: typeof TosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/': {
      id: '/api/auth/discord/'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord/'
      preLoaderRoute: typeof ApiAuthDiscordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/api/auth/discord/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  LinkRoute: LinkRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  TosIndexRoute: TosIndexRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
  ApiAuthDiscordIndexRoute: ApiAuthDiscordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
